=== AMWA-TV/is-11/APIs/schemas/media_profile_video.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": [
    "frame_width",
    "frame_height",
    "grain_rate"
  ],
  "properties": {
    "color_sampling": {
      "description": "Identifies the acceptable color (sub-)sampling mode of a video stream. It is complementary to Receiver Caps Parameter Constraint of the same name.",
      "type": "string",
      "enum": [
        "RGB",
        "YCbCr-4:4:4",
        "YCbCr-4:2:2",
        "YCbCr-4:2:0"
      ]
    },
    "component_depth": {
      "description": "Identifies the acceptable number of bits per component sample of a video stream. It is complementary to Receiver Caps Parameter Constraint of the same name.",
      "type": "integer"
    },
    "frame_width": {
      "description" : "Width of the picture in pixels",
      "type" : "integer"
    },
    "frame_height" : {
      "description" : "Height of the picture in pixels",
      "type" : "integer"
    },
    "interlace_mode" : {
      "description" : "Interlaced video mode for frames in this Flow",
      "type" : "string",
      "default": "progressive",
      "enum" : [
        "progressive",
        "interlaced_tff",
        "interlaced_bff",
        "interlaced_psf"
      ]
    },
    "media_type": {
      "description": "Subclassification of the format using IANA assigned media types",
      "type": "string",
      "anyOf": [
        {
          "enum": [
            "video/raw",
            "video/H264",
            "video/vc2"
          ]
        },
        {
          "pattern": "^video\\/[^\\s\\/]+$"
        }
      ]
    },
    "grain_rate" : {
      "description": "Number of Grains per second for this Flow. Must be an integer division of, or equal to the Grain rate specified by the parent Source. Grain rate matches the frame rate for video (see NMOS Content Model). Specified for periodic Flows only.",
      "type": "object",
      "required" : [
        "numerator"
      ],
      "properties" : {
        "numerator" : {
          "description" : "Numerator",
          "type" : "integer"
        },
        "denominator" : {
          "description" : "Denominator",
          "type" : "integer",
          "default" : 1
        }
      }
    }
  },
  "additionalProperties": false
}

=== AMWA-TV/is-11/examples/media-profiles-get-200.json
[
  {
    "color_sampling": "RGB",
    "component_depth": 8,
    "frame_width": 720,
    "frame_height": 400,
    "grain_rate": {
      "numerator": 70
    }
  },
  {
    "color_sampling": "RGB",
    "component_depth": 8,
    "frame_width": 640,
    "frame_height": 480,
    "grain_rate": {
      "numerator": 60
    }
  },
  {
    "color_sampling": "RGB",
    "component_depth": 8,
    "frame_width": 640,
    "frame_height": 480,
    "grain_rate": {
      "numerator": 67
    }
  },
  {
    "color_sampling": "RGB",
    "component_depth": 8,
    "frame_width": 640,
    "frame_height": 480,
    "grain_rate": {
      "numerator": 72
    }
  },
  {
    "color_sampling": "RGB",
    "component_depth": 8,
    "frame_width": 640,
    "frame_height": 480,
    "grain_rate": {
      "numerator": 75
    }
  },
  {
    "color_sampling": "RGB",
    "component_depth": 8,
    "frame_width": 800,
    "frame_height": 600,
    "grain_rate": {
      "numerator": 56
    }
  },
  {
    "color_sampling": "RGB",
    "component_depth": 8,
    "frame_width": 800,
    "frame_height": 600,
    "grain_rate": {
      "numerator": 60
    }
  },
  {
    "color_sampling": "RGB",
    "component_depth": 8,
    "frame_width": 800,
    "frame_height": 600,
    "grain_rate": {
      "numerator": 72
    }
  },
  {
    "color_sampling": "RGB",
    "component_depth": 8,
    "frame_width": 800,
    "frame_height": 600,
    "grain_rate": {
      "numerator": 75
    }
  },
  {
    "color_sampling": "RGB",
    "component_depth": 8,
    "frame_width": 832,
    "frame_height": 624,
    "grain_rate": {
      "numerator": 75
    }
  },
  {
    "color_sampling": "RGB",
    "component_depth": 8,
    "frame_width": 1024,
    "frame_height": 768,
    "grain_rate": {
      "numerator": 60
    }
  },
  {
    "color_sampling": "RGB",
    "component_depth": 8,
    "frame_width": 1024,
    "frame_height": 768,
    "grain_rate": {
      "numerator": 70
    }
  },
  {
    "color_sampling": "RGB",
    "component_depth": 8,
    "frame_width": 1024,
    "frame_height": 768,
    "grain_rate": {
      "numerator": 75
    }
  },
  {
    "color_sampling": "RGB",
    "component_depth": 8,
    "frame_width": 1280,
    "frame_height": 1024,
    "grain_rate": {
      "numerator": 75
    }
  },
  {
    "color_sampling": "RGB",
    "component_depth": 8,
    "frame_width": 1152,
    "frame_height": 870,
    "grain_rate": {
      "numerator": 75
    }
  }
]
